#!/bin/sh
# Very simple wrapper for sdlmess
SDLMESS_HOME=$HOME/.sdlmess
SDLMESS_BIN=sdlmess.real
SDLMESS_DATA=/usr/share/games/sdlmess
FONT_FILE=ui.bdf

#create a working directory for sdlmess to write its files
if [ ! -d $SDLMESS_HOME ]; then
 mkdir $SDLMESS_HOME;
fi;
if [ -d $SDLMESS_HOME ]; then
 cd $SDLMESS_HOME;
else
 echo Some error occured when trying to reach $SDLMESS_HOME;
 exit;
fi;
if [ ! -x `which $SDLMESS_BIN` ]; then
 echo Could not find sdlmess binary;
 exit;
fi;

#cheat engine should work for sdlmess
#but it misses a cheat.dat
#(crc issues prevent cheats to work with all dumps)

# use a locale keymap if it exists
KEYMAP_FILE=$SDLMESS_DATA/keymaps/km-`echo $LANG | cut -d_ -f1`.txt
if [ -f $KEYMAP_FILE ]; then
 KEYMAP="-keymap -keymap_file $KEYMAP_FILE";
fi;

#link to the bdf font
if [ ! -e $SDLMESS_HOME/$FONT_FILE ]; then
  ln -s $SDLMESS_DATA/$FONT_FILE $FONT_FILE;
fi;

$SDLMESS_BIN $KEYMAP "$@"


